2017-03-10 15:46:19,761 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-10 16:00:21,771 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-11 23:37:42,849 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-11 23:38:04,935 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-12 22:52:26,399 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-12 23:42:05,640 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-12 23:42:48,953 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 00:21:31,777 ERROR: Exception on /user/dup3 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 94, in user
    ]
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/user.html", line 12, in block "content"
    <p>{{ user.followers.count() }} followers |
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followers'
2017-03-13 00:23:00,499 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 11:21:38,199 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 27, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2017-03-13 12:01:57,628 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 12:02:06,297 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 27, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2017-03-13 12:02:18,638 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 27, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2017-03-13 12:06:28,960 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 27, in index
    'body': 'The Avengers movie was so cool!'
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/index.html", line 7, in block "content"
    {{ form.hidden_tag() }}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2017-03-13 12:06:37,906 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 13:31:32,201 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 13:41:17,315 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 14:16:39,830 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 14:31:21,309 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 26, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 31, in template
    {% endblock %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2017-03-13 14:31:31,997 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 14:31:35,378 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 26, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 31, in template
    {% endblock %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 198, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2017-03-13 15:04:12,769 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 15:04:16,769 ERROR: Exception on /user/dup3 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 94, in user
    form=form,
NameError: name 'form' is not defined
2017-03-13 15:04:26,194 ERROR: Exception on /user/dup3/1 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 94, in user
    form=form,
NameError: name 'form' is not defined
2017-03-13 15:04:59,345 ERROR: Exception on /user/dup3 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 94, in user
    posts=posts)
NameError: name 'form' is not defined
2017-03-13 15:05:06,055 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 15:05:25,531 ERROR: Exception on /user/dup3/2 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 91, in user
    posts = user.posts.paginate(page, POSTS_PER_PAGE, False)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 476, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2679, in all
    return list(self)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1046, in _execute_clauseelement
    if not self.schema_for_object.is_default else None)
  File "<string>", line 1, in <lambda>
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 436, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 442, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/dialects/mssql/base.py", line 1107, in __init__
    super(MSSQLCompiler, self).__init__(*args, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 435, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 216, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/dialects/mssql/base.py", line 1192, in visit_select
    raise exc.CompileError('MSSQL requires an order_by when '
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause
2017-03-13 15:06:55,730 ERROR: Exception on /user/dup3/2 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 91, in user
    posts = user.posts.paginate(page, POSTS_PER_PAGE, False)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 476, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2679, in all
    return list(self)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1046, in _execute_clauseelement
    if not self.schema_for_object.is_default else None)
  File "<string>", line 1, in <lambda>
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 436, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 442, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/dialects/mssql/base.py", line 1107, in __init__
    super(MSSQLCompiler, self).__init__(*args, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 435, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 216, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/compiler.py", line 242, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/dialects/mssql/base.py", line 1192, in visit_select
    raise exc.CompileError('MSSQL requires an order_by when '
sqlalchemy.exc.CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause
2017-03-13 15:25:17,920 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 15:25:53,428 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 17:01:17,072 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 17:15:02,618 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 17:25:53,566 ERROR: Exception on /index [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 26, in index
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 14, in top-level template code
    | <form style="display: inline;" action="{{ url_for('search') }}" method="post" name="search">{{ g.search_form.hidden_tag() }}{{ g.search_form.search(size=20) }}<input type="submit" value="Search"></form>
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/werkzeug/routing.py", line 1758, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'search'. Did you mean 'user' instead?
2017-03-13 17:27:05,877 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:44]
2017-03-13 17:27:20,537 ERROR: Exception on /search_results/asdf [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 161, in search_results
    results = Post.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
AttributeError: 'BaseQuery' object has no attribute 'whoosh_search'
2017-03-13 17:27:37,929 ERROR: Exception on /search_results/post [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 161, in search_results
    results = Post.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
AttributeError: 'BaseQuery' object has no attribute 'whoosh_search'
2017-03-14 10:40:03,234 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:45]
2017-03-14 11:24:31,226 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:47]
2017-03-14 11:54:52,243 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:47]
2017-03-14 12:05:32,649 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:47]
2017-03-24 23:56:48,892 ERROR: Exception on /search_results/asdf [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 163, in search_results
    results = Post.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
AttributeError: 'BaseQuery' object has no attribute 'whoosh_search'
2017-03-25 00:09:43,345 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_openid.py", line 500, in decorated
    return f(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 41, in login
    providers=app.config['OPENID_PROVIDERS'])
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/login.html", line 18, in block "content"
    {% include 'flash.html' %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flash.html
2017-03-25 00:09:47,330 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_openid.py", line 500, in decorated
    return f(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 41, in login
    providers=app.config['OPENID_PROVIDERS'])
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/login.html", line 18, in block "content"
    {% include 'flash.html' %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flash.html
2017-03-25 00:09:51,364 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_openid.py", line 500, in decorated
    return f(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 41, in login
    providers=app.config['OPENID_PROVIDERS'])
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/login.html", line 18, in block "content"
    {% include 'flash.html' %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flash.html
2017-03-25 00:09:55,783 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_openid.py", line 500, in decorated
    return f(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 41, in login
    providers=app.config['OPENID_PROVIDERS'])
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/login.html", line 18, in block "content"
    {% include 'flash.html' %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flash.html
2017-03-25 00:10:01,868 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_openid.py", line 500, in decorated
    return f(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 41, in login
    providers=app.config['OPENID_PROVIDERS'])
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/login.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/login.html", line 18, in block "content"
    {% include 'flash.html' %}
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: flash.html
2017-03-26 22:56:45,631 ERROR: Exception on /user/dup3 [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 96, in user
    posts=posts)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/srv/proj/flask/microblog/app/templates/base.html", line 42, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/proj/flask/microblog/app/templates/user.html", line 12, in block "content"
    {% if user.last_seen %}<p><em>Last seen: {{ momentjs(user.last_seen).calendar() }}</em></p>{% endif %}
jinja2.exceptions.UndefinedError: 'momentjs' is undefined
2017-03-26 23:02:12,092 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:48]
2017-03-27 10:08:33,663 ERROR: Exception on /search_results/post [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/srv/proj/flask/microblog/app/views.py", line 163, in search_results
    results = Post.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
AttributeError: 'BaseQuery' object has no attribute 'whoosh_search'
2017-03-28 15:09:17,615 INFO: microblog startup [in /srv/proj/flask/microblog/app/__init__.py:55]
2017-04-06 12:26:04,840 ERROR: Exception on /login [GET] [in /srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
pyodbc.Error: ('08S01', '[08S01] [FreeTDS][SQL Server]Write to the server failed (20006) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/srv/proj/flask/microblog/app/views.py", line 77, in before_request
    if g.user.is_authenticated:
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/login_manager.py", line 317, in _load_user
    return self.reload_user()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/flask_login/login_manager.py", line 279, in reload_user
    user = self.user_callback(user_id)
  File "/srv/proj/flask/microblog/app/views.py", line 48, in load_user
    return User.query.get(int(id))
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 859, in get
    return self._get_impl(ident, loading.load_on_ident)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 892, in _get_impl
    return fallback_fn(self, key)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
    return q.one()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2790, in one
    ret = self.one_or_none()
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2760, in one_or_none
    ret = list(self)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/srv/proj/flask/microblog/env/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('08S01', '[08S01] [FreeTDS][SQL Server]Write to the server failed (20006) (SQLExecDirectW)') [SQL: 'SELECT [user].id AS user_id, [user].nickname AS user_nickname, [user].email AS user_email, [user].about_me AS user_about_me, [user].last_seen AS user_last_seen \nFROM [user] \nWHERE [user].id = ?'] [parameters: (1,)]
